name: 'ilert deployment events'
description: 'Create an ilert deployment event'
inputs:
  integration-key:
    description: 'The integration key that identifies the deployment pipeline the event relates to.'
    required: true
  custom-event:
    description: 'Custom event summary. If provided the GitHub event type is ignored and the given summary used. A link to the run is included in the event.'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: "box"
  color: "blue"